# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BookHeroProjectDesigner/ecranacceuil.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1426, 903)
        self.bgwidget = QtWidgets.QWidget(MainWindow)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1451, 911))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background: qlineargradient(spread:pad, x1:0.091, y1:0.101636, x2:0.991379, y2:0.977, stop:0 rgba(100, 25, 2, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(618, 140, 151, 71))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(508, 230, 391, 41))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.connectionbtn = QtWidgets.QPushButton(self.bgwidget)
        self.connectionbtn.setGeometry(QtCore.QRect(510, 580, 341, 51))
        self.connectionbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.connectionbtn.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.connectionbtn.setObjectName("connectionbtn")
        self.hostfield = QtWidgets.QLineEdit(self.bgwidget)
        self.hostfield.setGeometry(QtCore.QRect(520, 320, 341, 51))
        self.hostfield.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.hostfield.setObjectName("hostfield")
        self.portfield = QtWidgets.QLineEdit(self.bgwidget)
        self.portfield.setGeometry(QtCore.QRect(870, 320, 121, 51))
        self.portfield.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.portfield.setObjectName("portfield")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(520, 300, 81, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(870, 300, 81, 20))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(440, 456, 341, 20))
        self.error.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; color:red;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.userfield = QtWidgets.QLineEdit(self.bgwidget)
        self.userfield.setGeometry(QtCore.QRect(520, 408, 341, 51))
        self.userfield.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.userfield.setObjectName("userfield")
        self.label_5 = QtWidgets.QLabel(self.bgwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 388, 81, 20))
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.passwordfield = QtWidgets.QLineEdit(self.bgwidget)
        self.passwordfield.setGeometry(QtCore.QRect(520, 500, 341, 51))
        self.passwordfield.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.passwordfield.setObjectName("passwordfield")
        self.label_6 = QtWidgets.QLabel(self.bgwidget)
        self.label_6.setGeometry(QtCore.QRect(520, 480, 81, 20))
        self.label_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.label.setText(_translate("MainWindow", "PyCrud"))
        self.label_2.setText(_translate("MainWindow", "Entrer les informations de connection"))
        self.connectionbtn.setText(_translate("MainWindow", "Connection"))
        self.hostfield.setText(_translate("MainWindow", "localhost"))
        self.portfield.setText(_translate("MainWindow", "3306"))
        self.label_3.setText(_translate("MainWindow", "Hôte"))
        self.label_4.setText(_translate("MainWindow", "Port"))
        self.userfield.setText(_translate("MainWindow", "root"))
        self.label_5.setText(_translate("MainWindow", "Usager"))
        self.passwordfield.setText(_translate("MainWindow", "********"))
        self.label_6.setText(_translate("MainWindow", "Mot de passe"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
