# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BookHeroProjectDesigner/selectionchapitres.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EcranDeveloppeur(object):
    def setupUi(self, EcranDeveloppeur):
        EcranDeveloppeur.setObjectName("EcranDeveloppeur")
        EcranDeveloppeur.resize(1414, 903)
        self.bgwidget = QtWidgets.QWidget(EcranDeveloppeur)
        self.bgwidget.setGeometry(QtCore.QRect(-10, 0, 1451, 911))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background: qlineargradient(spread:pad, x1:0.091, y1:0.101636, x2:0.991379, y2:0.977, stop:0 rgba(100, 25, 2, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.bgwidget.setObjectName("bgwidget")
        self.ecran_affichage_chapitre_textBrowser = QtWidgets.QTextBrowser(self.bgwidget)
        self.ecran_affichage_chapitre_textBrowser.setGeometry(QtCore.QRect(50, 170, 1341, 621))
        self.ecran_affichage_chapitre_textBrowser.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ecran_affichage_chapitre_textBrowser.setReadOnly(True)
        self.ecran_affichage_chapitre_textBrowser.setTabStopWidth(82)
        self.ecran_affichage_chapitre_textBrowser.setTabStopDistance(82.0)
        self.ecran_affichage_chapitre_textBrowser.setObjectName("ecran_affichage_chapitre_textBrowser")
        self.page_precedente_pushButton_2 = QtWidgets.QPushButton(self.bgwidget)
        self.page_precedente_pushButton_2.setGeometry(QtCore.QRect(500, 830, 151, 51))
        self.page_precedente_pushButton_2.setObjectName("page_precedente_pushButton_2")
        self.page_suivante_pushButton_3 = QtWidgets.QPushButton(self.bgwidget)
        self.page_suivante_pushButton_3.setGeometry(QtCore.QRect(770, 830, 151, 51))
        self.page_suivante_pushButton_3.setObjectName("page_suivante_pushButton_3")
        self.selection_chapitre_comboBox = QtWidgets.QComboBox(self.bgwidget)
        self.selection_chapitre_comboBox.setGeometry(QtCore.QRect(350, 70, 671, 31))
        self.selection_chapitre_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.selection_chapitre_comboBox.setMouseTracking(False)
        self.selection_chapitre_comboBox.setTabletTracking(False)
        self.selection_chapitre_comboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.selection_chapitre_comboBox.setMaxVisibleItems(15)
        self.selection_chapitre_comboBox.setMinimumContentsLength(1)
        self.selection_chapitre_comboBox.setObjectName("selection_chapitre_comboBox")
        self.retour_accueil_pushButton = QtWidgets.QPushButton(self.bgwidget)
        self.retour_accueil_pushButton.setGeometry(QtCore.QRect(70, 40, 151, 81))
        self.retour_accueil_pushButton.setObjectName("retour_accueil_pushButton")

        self.retranslateUi(EcranDeveloppeur)
        QtCore.QMetaObject.connectSlotsByName(EcranDeveloppeur)

    def retranslateUi(self, EcranDeveloppeur):
        _translate = QtCore.QCoreApplication.translate
        EcranDeveloppeur.setWindowTitle(_translate("EcranDeveloppeur", "Dialog"))
        self.ecran_affichage_chapitre_textBrowser.setHtml(_translate("EcranDeveloppeur", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.page_precedente_pushButton_2.setText(_translate("EcranDeveloppeur", "Précédente"))
        self.page_suivante_pushButton_3.setText(_translate("EcranDeveloppeur", "Suivante"))
        self.retour_accueil_pushButton.setText(_translate("EcranDeveloppeur", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EcranDeveloppeur = QtWidgets.QDialog()
    ui = Ui_EcranDeveloppeur()
    ui.setupUi(EcranDeveloppeur)
    EcranDeveloppeur.show()
    sys.exit(app.exec_())
