# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BookHeroProjectDesigner/ecranacceuil.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EcranAcceuil(object):
    def setupUi(self, EcranAcceuil):
        EcranAcceuil.setObjectName("EcranAcceuil")
        EcranAcceuil.resize(1426, 903)
        self.bgwidget = QtWidgets.QWidget(EcranAcceuil)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1451, 911))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background: qlineargradient(spread:pad, x1:0.091, y1:0.101636, x2:0.991379, y2:0.977, stop:0 rgba(100, 25, 2, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}\n"
"")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(500, 120, 401, 71))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 220, 391, 41))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.connectionpushButton = QtWidgets.QPushButton(self.bgwidget)
        self.connectionpushButton.setGeometry(QtCore.QRect(520, 500, 341, 51))
        self.connectionpushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.connectionpushButton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.connectionpushButton.setObjectName("connectionpushButton")
        self.motdepasse_lineEdit = QtWidgets.QLineEdit(self.bgwidget)
        self.motdepasse_lineEdit.setGeometry(QtCore.QRect(520, 431, 341, 51))
        self.motdepasse_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.motdepasse_lineEdit.setObjectName("motdepasse_lineEdit")
        self.label_courriel = QtWidgets.QLabel(self.bgwidget)
        self.label_courriel.setGeometry(QtCore.QRect(523, 305, 131, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_courriel.setFont(font)
        self.label_courriel.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_courriel.setObjectName("label_courriel")
        self.courriel_lineEdit = QtWidgets.QLineEdit(self.bgwidget)
        self.courriel_lineEdit.setGeometry(QtCore.QRect(520, 330, 341, 51))
        self.courriel_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.courriel_lineEdit.setObjectName("courriel_lineEdit")
        self.label_mdp = QtWidgets.QLabel(self.bgwidget)
        self.label_mdp.setGeometry(QtCore.QRect(521, 407, 131, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_mdp.setFont(font)
        self.label_mdp.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_mdp.setObjectName("label_mdp")
        self.label_mauvaise_infos = QtWidgets.QLabel(self.bgwidget)
        self.label_mauvaise_infos.setEnabled(True)
        self.label_mauvaise_infos.setGeometry(QtCore.QRect(450, 570, 491, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_mauvaise_infos.setFont(font)
        self.label_mauvaise_infos.setAutoFillBackground(False)
        self.label_mauvaise_infos.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: red;\n"
"background: rgba(10,10,10,55);")
        self.label_mauvaise_infos.setFrameShape(QtWidgets.QFrame.Box)
        self.label_mauvaise_infos.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_mauvaise_infos.setLineWidth(-1)
        self.label_mauvaise_infos.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mauvaise_infos.setObjectName("label_mauvaise_infos")

        self.retranslateUi(EcranAcceuil)
        QtCore.QMetaObject.connectSlotsByName(EcranAcceuil)

    def retranslateUi(self, EcranAcceuil):
        _translate = QtCore.QCoreApplication.translate
        EcranAcceuil.setWindowTitle(_translate("EcranAcceuil", "Dialog"))
        self.label.setText(_translate("EcranAcceuil", "Python Book Hero"))
        self.label_2.setText(_translate("EcranAcceuil", "Entrez vos informations de connection"))
        self.connectionpushButton.setText(_translate("EcranAcceuil", "Connection"))
        self.motdepasse_lineEdit.setText(_translate("EcranAcceuil", "qwerty123"))
        self.label_courriel.setText(_translate("EcranAcceuil", "Courriel"))
        self.courriel_lineEdit.setText(_translate("EcranAcceuil", "triangle1232009@hotmail.com"))
        self.label_mdp.setText(_translate("EcranAcceuil", "Mot de passe"))
        self.label_mauvaise_infos.setText(_translate("EcranAcceuil", "* Oups, cette combinaison n\'à pu être retrouvée."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EcranAcceuil = QtWidgets.QDialog()
    ui = Ui_EcranAcceuil()
    ui.setupUi(EcranAcceuil)
    EcranAcceuil.show()
    sys.exit(app.exec_())
