# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BookHeroProjectDesigner/selectionchapitres.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EcranChapitres(object):
    def setupUi(self, EcranChapitres):
        EcranChapitres.setObjectName("EcranChapitres")
        EcranChapitres.resize(1054, 858)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EcranChapitres.sizePolicy().hasHeightForWidth())
        EcranChapitres.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(EcranChapitres)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bgwidget = QtWidgets.QWidget(EcranChapitres)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bgwidget.sizePolicy().hasHeightForWidth())
        self.bgwidget.setSizePolicy(sizePolicy)
        self.bgwidget.setAutoFillBackground(False)
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background: qlineargradient(spread:pad, x1:0.091, y1:0.101636, x2:0.991379, y2:0.977, stop:0 rgba(100, 25, 2, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.bgwidget.setObjectName("bgwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bgwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.bgwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setStyleSheet("border-style: none;\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.retour_accueil_pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.retour_accueil_pushButton.sizePolicy().hasHeightForWidth())
        self.retour_accueil_pushButton.setSizePolicy(sizePolicy)
        self.retour_accueil_pushButton.setMinimumSize(QtCore.QSize(150, 100))
        self.retour_accueil_pushButton.setMaximumSize(QtCore.QSize(150, 100))
        self.retour_accueil_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.retour_accueil_pushButton.setStyleSheet(":active{\n"
"border-style: 1px;\n"
"background: rgb(204,204,204);\n"
"}\n"
":hover{\n"
"border-style: 1px;\n"
"background: rgb(100,255,100);\n"
"}\n"
"")
        self.retour_accueil_pushButton.setObjectName("retour_accueil_pushButton")
        self.horizontalLayout_2.addWidget(self.retour_accueil_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.selection_chapitre_comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selection_chapitre_comboBox_2.sizePolicy().hasHeightForWidth())
        self.selection_chapitre_comboBox_2.setSizePolicy(sizePolicy)
        self.selection_chapitre_comboBox_2.setMinimumSize(QtCore.QSize(300, 25))
        self.selection_chapitre_comboBox_2.setMaximumSize(QtCore.QSize(600, 40))
        self.selection_chapitre_comboBox_2.setBaseSize(QtCore.QSize(0, 50))
        self.selection_chapitre_comboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.selection_chapitre_comboBox_2.setMouseTracking(False)
        self.selection_chapitre_comboBox_2.setTabletTracking(False)
        self.selection_chapitre_comboBox_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.selection_chapitre_comboBox_2.setStyleSheet(":active{\n"
"border-style: 3px black;\n"
"background: rgb(255,255,255);\n"
"}\n"
":hover{\n"
"border-style: 3px black;\n"
"background: rgb(204,255,229);\n"
"}")
        self.selection_chapitre_comboBox_2.setMaxVisibleItems(15)
        self.selection_chapitre_comboBox_2.setMinimumContentsLength(1)
        self.selection_chapitre_comboBox_2.setObjectName("selection_chapitre_comboBox_2")
        self.horizontalLayout_2.addWidget(self.selection_chapitre_comboBox_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.bgwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setStyleSheet("border-style: none;\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ecran_affichage_chapitre_textBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.ecran_affichage_chapitre_textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.ecran_affichage_chapitre_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ecran_affichage_chapitre_textBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.ecran_affichage_chapitre_textBrowser.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ecran_affichage_chapitre_textBrowser.setReadOnly(True)
        self.ecran_affichage_chapitre_textBrowser.setTabStopWidth(82)
        self.ecran_affichage_chapitre_textBrowser.setTabStopDistance(82.0)
        self.ecran_affichage_chapitre_textBrowser.setOpenExternalLinks(False)
        self.ecran_affichage_chapitre_textBrowser.setObjectName("ecran_affichage_chapitre_textBrowser")
        self.horizontalLayout_3.addWidget(self.ecran_affichage_chapitre_textBrowser)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.bgwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet("border-style: none;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.page_precedente_pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_precedente_pushButton_2.sizePolicy().hasHeightForWidth())
        self.page_precedente_pushButton_2.setSizePolicy(sizePolicy)
        self.page_precedente_pushButton_2.setMinimumSize(QtCore.QSize(200, 50))
        self.page_precedente_pushButton_2.setMaximumSize(QtCore.QSize(300, 50))
        self.page_precedente_pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.page_precedente_pushButton_2.setStyleSheet(":active{\n"
"border-style: 1px;\n"
"background: rgb(204,204,204);\n"
"\n"
"}\n"
":hover{\n"
"border-style: 1px;\n"
"background: rgb(100,255,100);\n"
"}\n"
"")
        self.page_precedente_pushButton_2.setObjectName("page_precedente_pushButton_2")
        self.horizontalLayout.addWidget(self.page_precedente_pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(221, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.page_suivante_pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_suivante_pushButton_3.sizePolicy().hasHeightForWidth())
        self.page_suivante_pushButton_3.setSizePolicy(sizePolicy)
        self.page_suivante_pushButton_3.setMinimumSize(QtCore.QSize(200, 50))
        self.page_suivante_pushButton_3.setMaximumSize(QtCore.QSize(300, 50))
        self.page_suivante_pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.page_suivante_pushButton_3.setStyleSheet(":active{\n"
"border-style: 1px;\n"
"background: rgb(204,204,204);\n"
"}\n"
":hover{\n"
"border-style: 1px;\n"
"background: rgb(100,255,100);\n"
"}\n"
"")
        self.page_suivante_pushButton_3.setObjectName("page_suivante_pushButton_3")
        self.horizontalLayout.addWidget(self.page_suivante_pushButton_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.bgwidget)

        self.retranslateUi(EcranChapitres)
        QtCore.QMetaObject.connectSlotsByName(EcranChapitres)

    def retranslateUi(self, EcranChapitres):
        _translate = QtCore.QCoreApplication.translate
        EcranChapitres.setWindowTitle(_translate("EcranChapitres", "Dialog"))
        self.retour_accueil_pushButton.setText(_translate("EcranChapitres", "Acceuil"))
        self.ecran_affichage_chapitre_textBrowser.setHtml(_translate("EcranChapitres", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.page_precedente_pushButton_2.setText(_translate("EcranChapitres", "Précédente"))
        self.page_suivante_pushButton_3.setText(_translate("EcranChapitres", "Suivante"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EcranChapitres = QtWidgets.QDialog()
    ui = Ui_EcranChapitres()
    ui.setupUi(EcranChapitres)
    EcranChapitres.show()
    sys.exit(app.exec_())
